---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-proxy
  namespace: prometheus
  labels:
    app: prometheus-proxy
spec:
  ports:
  - port: 9190
    protocol: TCP
    name: prometheus
  - port: 9290
    protocol: TCP
    name: prometheus-kpi
  selector:
    app: prometheus-proxy
