---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: prometheus-master
  name: prometheus-master
spec:
  selector:
    prometheus-type: master
  ports:
  - name: http
    protocol: TCP
    port: 9090
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: prometheus-slave
  name: prometheus-slave
spec:
  selector:
    prometheus-type: slave
  ports:
  - name: http
    protocol: TCP
    port: 9090
